// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {kubernetesconfig} from '../models';
import {cluster} from '../models';
import {pod} from '../models';

export function ChangeContext(arg1:string):Promise<void>;

export function GetDeployment(arg1:string,arg2:string):Promise<string>;

export function GetKubernetesContext():Promise<kubernetesconfig.KubeContexts>;

export function GetLogsFromPod(arg1:string,arg2:string,arg3:number):Promise<string>;

export function GetNamespaces():Promise<cluster.ClusterNamespaces>;

export function GetPodMetadata(arg1:string,arg2:string):Promise<pod.PodInfo>;

export function GetPodsFromNamespace(arg1:string):Promise<Array<pod.PodListMetadata>>;
