// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeContext(arg1) {
  return window['go']['main']['App']['ChangeContext'](arg1);
}

export function GetKubernetesContext() {
  return window['go']['main']['App']['GetKubernetesContext']();
}

export function GetLogsFromPod(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetLogsFromPod'](arg1, arg2, arg3);
}

export function GetNamespaces() {
  return window['go']['main']['App']['GetNamespaces']();
}

export function GetPodMetadata(arg1, arg2) {
  return window['go']['main']['App']['GetPodMetadata'](arg1, arg2);
}

export function GetPodsFromNamespace(arg1) {
  return window['go']['main']['App']['GetPodsFromNamespace'](arg1);
}
