name: Build & Test Backend
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .

      - name: Install Wails CLI
        run: |
          go get github.com/wailsapp/wails/cmd/wails@latest
          go install github.com/wailsapp/wails/cmd/wails@latest

      - name: Build Wheelie
        run: wails build

      - name: Test with the Go CLI
        run: go test
