name: Build
on: push
jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./frontend
      run: npm install
    - name: Build App
      working-directory: ./frontend
      run: npm run build

  backend:
    strategy:
      fail-fast: false
      matrix:
        build: [
          {name: Wheelie, platform: linux/amd64, os: ubuntu-latest},
          {name: Wheelie, platform: windows/amd64, os: windows-latest},
          {name: Wheelie, platform: darwin/universal, os: macos-latest}
        ]
    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: dAppServer/wails-build-action@v2.2
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}

